### ISSUE TITLE
Vscode-editor Plugin 

### ISSUE THREAD

**Issue by likemuuxi** [Aetherinox/obsidian-dataview-snippets#2]
Plugin Name: 
[vscode-editor](https://github.com/sunxvming/obsidian-vscode-editor)

Plugin modification: 
Replace CSS files after installing plugins
[styles.zip](https://github.com/Aetherinox/obsidian-dataview-snippets/files/14373351/styles.zip)

You can also leave the CSS unchanged, if you prefer the default color of the plugin

**Comment by Aetherinox** [comment]
Oh wow, this is much better.
I wonder how I even missed this plugin. I usually watch the plugin section pretty good. 

Thanks a crap ton, this is way better. I couldn't see crap on the other plugin, everything was black, on top of a dark grey background.

You're a god.

**Comment by likemuuxi** [comment]
I am glad to solve your problem, and I also love this plugin very much because it has faster speed and can run on mobile devices

**Comment by likemuuxi** [comment]
And I completely understand your excitement - it's like getting an unexpected gift, isn't it?

By the way, I wanted to share with you that your dataview-snippets in the repository has been incredibly helpful to me. It's a fantastic resource and I appreciate the effort you've put into it.

**Comment by Aetherinox** [comment]
Glad you like it.

I use them daily, especially the "Tags" and "Table of Contents".
I'll probably add some more later when I get some time.
